{
    "0": "Galactic Sign \"Ray of darkness\"",
    "1": "Nocturne deer \"Lethal Antlers\"",
    "2": "Nocturne Deer \"Antlers Trap\"",
    "3": "Sello Helado \"Icicle Fall\"",
    "4": "Sello de Granizo \"Hailstorm\"",
    "5": "Sello Gélido \"Perfect Freeze\"",
    "6": "Sello Níveo \"Diamond Blizzard\"",
    "7": "Sello Floral \"Hermosa y sublime flor\"",
    "8": "Sello Floral \"Selaginella 9\"",
    "9": "Sello Arcoíris \"Campanas de viento de siete colores\"",
    "10": "Sello Ilusorio \"Flor Imaginaria Yumezakura\"",
    "11": "Sello Colorido \"Lluvia multicolor\"",
    "12": "Sello Colorido \"Danza caótica de haces coloridos\"",
    "13": "Sello Colorido \"Tifón de deslumbrantes colores\"",
    "14": "Sello de Fuego \"Agni Shine\"",
    "15": "Sello de Agua \"Princess Undine\"",
    "16": "Sello de Madera \"Sylphy Horn\"",
    "17": "Sello de Tierra \"Lazy Trilithon\"",
    "18": "Sello de Metal \"Metal Fatigue\"",
    "19": "Sello de Fuego \"Agni Shine - Supremo\"",
    "20": "Sello de Madera \"Sylphy Horn - Supremo\"",
    "21": "Sello de Tierra \"Lazy Trilithon - Supremo\"",
    "22": "Sello de Fuego \"Agni Radiance\"",
    "23": "Sello de Agua \"Bury in Lake\"",
    "24": "Sello de Madera \"Green Storm\"",
    "25": "Sello de Tierra \"Trilithon Shake\"",
    "26": "Sello de Metal \"Silver Dragon\"",
    "27": "Sellos de Fuego y Tierra \"Lava Cromlech\"",
    "28": "Sellos de Madera y Fuego \"Forest Blaze\"",
    "29": "Sellos de Agua y Madera \"Water Elf”",
    "30": "Sellos de Metal y Agua \"Mercury Poison\"",
    "31": "Sellos de Tierra y Metal \"Emerald Megalith\"",
    "32": "Ilusionismo \"Distracción\"",
    "33": "Ilusionismo \"Distracción Cautivadora”",
    "34": "Presente Ilusorio \"Clock Corpse\"",
    "35": "Fenómeno Ilusorio \"Luna Clock\"",
    "36": "Técnica Secreta de Sirvienta \"Muñeca Marioneta\"",
    "37": "Fantasma Ilusorio \"Jack the Ludo Bile\"",
    "38": "Mundo Ilusorio \"The World\"",
    "39": "Técnica Secreta de Sirvienta \"Muñeca Asesina\"",
    "40": "Ilusionismo \"Eternal Meek\"",
    "41": "Castigo Celestial \"Star of David\"",
    "42": "Sello Tenebroso \"Inframundo Escarlata\"",
    "43": "Maleficio \"Maldición de Vlad Tepes\"",
    "44": "Sello Escarlata \"Scarlet Shoot\"",
    "45": "\"Red Magic\"",
    "46": "Castigo Divino \"Joven Señora de los demonios\"",
    "47": "Sello Infernal \"Montaña de las Mil Agujas\"",
    "48": "Arte Divino \"Ilusión Vampírica\"",
    "49": "Sello Escarlata \"Scarlet Meister\"",
    "50": "\"Gensokyo Escarlata\"",
    "51": "Sello Lunar \"Silent Selene\"",
    "52": "Sello Solar \"Royal Flare”",
    "53": "Sello de los Cinco Elementos “Piedra Filosofal”",
    "54": "Tabú \"Cranberry Trap\"",
    "55": "Tabú \"Lævateinn\"",
    "56": "Tabú \"Four of a Kind\"",
    "57": "Tabú \"Kagome, Kagome\"",
    "58": "Tabú \"Laberinto de Amor\"",
    "59": "Disparo Prohibido \"Starbow Break\"",
    "60": "Disparo Prohibido \"Catadioptric”",
    "61": "Disparo Prohibido \"Reloj que Aleja el Pasado\"",
    "62": "Disparo Secreto \"¿Y no quedará ninguno?\"",
    "63": "Q.E.D. \"Hamon de los 495 Años\""
}